# Generated by Django 3.0.3 on 2020-02-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title of Document')),
                ('body', models.CharField(blank=True, max_length=2048, verbose_name='Body of Document')),
            ],
        ),
    ]
